### ISSUE TITLE
Not working with files named index.html?

### ISSUE THREAD

**Issue by jedrichards** [songkick/replaceinfiles#1]
Hey I'm on Node 5.3.0. Seeing an odd behaviour. The following command works as expected, I see a file in dist with replaced contents:

```
cat map.json | node_modules/.bin/replaceinfiles -s static/foo.html -d 'dist/{base}'
```

If I rename the html file to `index.html` and try again,

```
cat map.json | node_modules/.bin/replaceinfiles -s static/index.html -d 'dist/{base}'
```

The file gets created in dist but the contents are not replaced. Any idea what's going on?

**Comment by ArnaudRinquin** [comment]
Do you mind providing an extract of your `map.json` and `index.html`? In the meantime, I'll try to reproduce something similar.

**Comment by jedrichards** [comment]
Yep sure. Sorry should have provided these the first time.

map.json

```
{"/main.css":"/main.cdfdc1.css","/bundle.js":"/bundle.78d67b.js"}
```

index.html

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/main.css" rel="stylesheet" type='text/css'>
  </head>
  <body>
    <p>1 + 1 is {{1 + 1}}</p>
    <hello-world name="Earth"></hello-world>
    <script src="/bundle.js"></script>
  </body>
</html>
```

**Comment by ArnaudRinquin** [comment]
So, I just reproduced your context in [this project](https://github.com/ArnaudRinquin/replaceinfiles-reproduce-1) without being able to reproduce the issue:

From [travis](https://travis-ci.org/ArnaudRinquin/replaceinfiles-reproduce-1/jobs/102602818), using node `5.3.0`:

```
> replaceinfiles-reproduce-1@0.0.0 pretest /home/travis/build/ArnaudRinquin/replaceinfiles-reproduce-1
> npm run build
> replaceinfiles-reproduce-1@0.0.0 build /home/travis/build/ArnaudRinquin/replaceinfiles-reproduce-1
> cat map.json | replaceinfiles -s static/index.html -d 'dist/{base}'
{
  "options": {
    "source": "static/index.html",
    "destPattern": "dist/{base}",
    "silent": false,
    "outputPath": null,
    "replaceMapPath": null,
    "replaceMap": {
      "hello": "goodbye",
      "world": "earth"
    },
    "encoding": "utf-8"
  },
  "result": [
    {
      "src": "static/index.html",
      "dest": "dist/index.html",
      "changed": true
    }
  ]
}
> replaceinfiles-reproduce-1@0.0.0 test /home/travis/build/ArnaudRinquin/replaceinfiles-reproduce-1
> diff dist/index.html expected/index.html

```

I'll update it with your settings.

**Comment by ArnaudRinquin** [comment]
As you can see in [travis](https://travis-ci.org/ArnaudRinquin/replaceinfiles-reproduce-1/jobs/102605226), I just updated the replication with your code and can't reproduce the issue.

**Comment by jedrichards** [comment]
Argh ok, I will do some more digging!

**Comment by ArnaudRinquin** [comment]
Sure! Let me know if you find anything!

**Comment by jedrichards** [comment]
Aye aye! Thanks so far :)
