### ISSUE TITLE
Add support for HanSON replace maps

### ISSUE THREAD

**Issue by RyanZim** [songkick/replaceinfiles#2]
I would like to use replaceinfiles to inject analytics codes into my HTML. One of JSON's limitations is the difficulty of using multi-line strings. HanSON is an extension to JSON that adds (among other things) ES6-style backtick-quoted multi-line strings.

**Example:**

```
{
  "input text": `some multi-line
output text`
}
```

All valid JSON is valid HanSON.

You can read more about it at https://github.com/timjansen/hanson.

Could replaceinfiles add support for HanSON replace maps?

I'd be willing to do a PR, just let me know!

**Comment by RyanZim** [comment]
@ArnaudRinquin bump.

**Comment by ArnaudRinquin** [comment]
If you can do it, feel free to submit a PR

Otherwise, I have no time for this.

Another way to do it is to use another CLI tool that would convert HanSON.

**Comment by RyanZim** [comment]
PR will be on the way!
