### ISSUE TITLE
A release was created but the version was not bumped in package.json

### ISSUE THREAD

**Issue by KrauseStefan** [songkick/replaceinfiles#5]
I was trying to pull the latest version of this library `v1.1.5` but kept on getting `v1.1.4`
I found out in the end that I did get the right version with git but npm reported it as `v1.1.4`

I see that this is because the version number has not been bumped in `package.json`, is this something that you would do?

**Comment by jackfranklin** [comment]
I suspect it was just forgotten that we need to do an `npm publish` after merging. @benhodgson87   is your person to ask to do that :)

**Comment by KrauseStefan** [comment]
Thanks
